set pydal < 20240427 in requirements.txt
version 20240427 breaks web2py 'login'

web2py/gluon/tools.py, line 2895, in login
    user = Row(table_user._filter_fields(user, id=True))
TypeError: _filter_fields() got an unexpected keyword argument 'id'